version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: db_jumarket_teste
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 58452574
      MYSQL_DATABASE: jumarket_db_teste
      MYSQL_USER: jorge
      MYSQL_PASSWORD: 58452574
    networks:
      - network
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:5.2.1
    container_name: admin_db_jumarket_teste
    restart: always
    ports:
      - '8091:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 58452574 
    networks:
      - network
networks:
  network: